# No es necesaria en versiones modernas de Docker Compose
# version: '3.8'

services:
  monitor_service:
    build: .
    container_name: monitor_service
    ports:
      - "8080:8080"
    volumes:
      - ./config/config.json:/app/config.json
    # --- ARREGLADO: Espera a que el healthcheck de la BD sea exitoso ---
    depends_on:
      mysql_db:
        condition: service_healthy
    environment:
      - MYSQL_HOST=mysql_db

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    # --- AÑADIDO: Healthcheck para verificar que MySQL está listo ---
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: monitoring
      MYSQL_USER: monitor
      MYSQL_PASSWORD: monitor123
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql